language: python
python:
  - "3.6" # current default Python on Travis CI
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover -v

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - cargo build --target "$TARGET" --release
  - git config --local user.name "Gabriel Barker"
  - git config --local user.email "$GITHUB_EMAIL"
  - name=$(bin/qual-id.sh -p bird-instrument)
  - tag="${name%\"}"
  - tag="${tag#\"}"
  - git tag $tag
  - mkdir $tag
  - cp bin/qual-id.sh $tag/
  - cp README.md LICENSE $tag/
  - tar czvf $tag.tar.gz $tag

deploy:
  provider: releases
  api_key:
    secure: Ggvv65x3DPow3Kx5p/owg/AU2L1GeOE8UE3cRoolh4NZQ3ytL2KNMOEW0AvCirZ5iLrgwfQLs/iLnr4U5MJksJyoeF/MmOdaOvIHeMQb4LYDqtzn5TxMRm5dDdGx7sf/J/2poHxqAgB/bEKY+tQuUxWQftTWIb25b+rI11tNr4pK5TEw0EvP0o4sRZAylyVFtUb4VpnKwL0+3t3raoRmPTnAa2fg2Pou8hwOpKlBbVeyBPkhWRE0kRxc3bAP+bWHmC6ZpB7p/2XljjMQkFHG7RelGm+F6q2gq2A/pvNPeBzIvmxY/5N6cs2LlR0oeW1AuNFDwWXIIBMywW3qRjXut2QyQusMo8qU16P/jb/HtMqZ3XOXE/5Ab/NQkx7K6iy+dX73wrPfIelovC6h4Zf4eRL67Ny9QoXIx3CfEKsvAFJf5EYsU52YvhYfHfwG4LEugIsi91Tx18ITU15sng01B+lycIjGMWh/hoaTQ96Xq6M0ri9vQJyC0P/rjHJwL10Zb9g1Kc3NyFKMjZY/vqS5sHZ8+TCRaLTTfTNakoSF60IFWzDCruZR9wxMAUofAO2qUC8ujvoPY+E6NET/83ETVzo/ohJPkgd/akup39WHE8WcL80GDhfp9/CI+b9cjLRgpxh70oHT3uioVZhNS99LmoXYiek0RFNgmNogz9qWpMg=
  file: $tag.tar.gz
  on:
    repo: gabrielbarker/qual-id
    branch: main
  skip_cleanup: true
